apiVersion: v1
kind: Service
metadata:
  name: pylogger-service
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  selector:
    app: pylogger
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{.Values.deployment.port}}
  type: ClusterIP
